name: bulma
description: 'The Bulma flexbox CSS framework converted to scss format in a dart
package.'
version: 0.8.0+4
homepage: https://github.com/ibexio/dart-bulma

environment:
  sdk: ">=2.4.0 <3.0.0"

dev_dependencies:
  sass_builder: ^2.1.3
  build_runner: ^1.7.2
  git: ^1.0.1
  pub_semver: ^1.4.2
